version: '3.8'

services: 

  database:
    build: 
      context: ./backend
      target: postgres
    container_name: inventory-database
    volumes:
      - db-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mrc201
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 25s
      retries: 5

  backend:
    container_name: inventory-backend
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    build:
      context: ./backend
      target: fastify
    command: bash -c "npx prisma db push && npx prisma generate && npm run dev"

  backend-n2:
    container_name: inventory-backend-n2
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    build:
      context: ./backend
      target: fastify
    command: bash -c "npx prisma generate && npm run dev"

  nginx:
    container_name: inventory-nginx
    restart: always
    depends_on:
      - frontend
      - backend
      - backend-n2
    build:
      context: ./nginx
    ports:
      - 8000:80

  frontend:
    container_name: inventory-frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/web
      - /usr/src/web/node_modules
    build:
      context: ./frontend
      target: react
    command: npm run dev


volumes:
  db-storage: